backend:
  name: git-gateway
  repo: rebelastronaut/popin
  branch: master


media_folder_relative: true
media_folder: src/pages/images
public_folder: ../images

collections:
  - name: "Events"
    label: "events"
    identifier_field: title
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "DD-MM-YYYY"}
      - { label: "Path", name: "path", widget: "string"}
      - { label: "Cover Image", name: "cover", widget: "image"}
      - { label: Gallery Images, name: "gallery", widget: list, fields: [{ label: Image, name: image, widget: image }]}
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "About"
    label: "about"
    identifier_field: title
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: true
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
        - { label: "Cover Image", name: "cover", widget: "image" }
        - { label: "Gallery Images", name: "gallery", widget: list, fields: [{label: Image, name: image, widget: image}]}
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime", format: "DD-MM-YYYY"}
        - { label: "Path", name: "path", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
