backend:
  name: git-gateway
  branch: master


media_folder_relative: true
media_folder: src/pages/events
# public_folder: /img

collections:
  - name: "Events"
    label: "events"
    identifier_field: title
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
    preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
        - label: CoverImage
          Name: CoverImage
          widget: image
          media_library:
            config:
              multiple: false
        - label: GalleryImage
          Name: Galleryt Image
          widget: image
          media_library:
            config:
              multiple: true
    - { label: "Body", name: "body", widget: "markdown" }
  - name: "About"
    label: "about"
    identifier_field: title
    folder: "src/pages/about"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: true
    fields:
    - label: "Images"
      name: "images"
      widget: "list"
      fields:
      - label: CoverImage
        Name: CoverImage
        widget: image
        media_library:
          config:
            multiple: false
      - label: GalleryImage
        Name: Galleryt Image
        widget: image
        media_library:
          config:
            multiple: true
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
